### PR TITLE
Fixes Issue #49 (Make it easier to get the amount of an XRP payment as BigDecimal)

### LINKED ISSUE #49: Make it easier to get the amount of an XRP payment as BigDecimal
The way amounts are mapped could be more convenient to use. In most cases, people just want to get the amount in XRP as a decimal, not drops. But on things like payments, that requires doing an` instanceof` then a cast to `XrpCurrencyAmount` then no obvious way to get the decimal value (instead of drops) from there

### PR DESCRIPTION
**Pull request by sappenin**
* Make it easier to get the amout of an XRP Payment as a BigDecimal.
* Improve the boundary checking of the XrpCurrencyAmount.
* Add unit test coverage.

Signed-off-by: David Fuelling <sappenin@gmail.com>

### CODE REVIEW

File: xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Payment.java [hunk 1]
```diff
@@ -41,14 +44,32 @@ default PaymentFlags flags() {
...
+   * A typed variant of {@link #amount()} which produces a value in XRP Drops if that result is an instance of {@link
+   * XrpCurrencyAmount}.
+   *
+   * @return The amount of this payment if this payment is denominated in XRP (i.e., if the result of calling {@link
+   *   #amount()} is an instance of {@link XrpCurrencyAmount}); otherwise, returns {@link Optional#empty()} (e.g., if
+   *   this payment is denominated in an Issued Currency).
+   */
+  @Derived
+  @JsonIgnore
+  default Optional<XrpCurrencyAmount> amountAsXrp() {
```
Comment (nkramer44) [inline xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Payment.java:65]: I liked your idea of providing a handler on `CurrencyAmount`.  The handler could work in tandem with an `amountAsXrp` method like this:
```java
payment.amount().handle(
  xrpCurrencyAmount -> xrpCurrencyAmount.toXrp(),
  issuedCurrencyAmount -> issuedCurrencyAmount
)
```

There are a few transactions that have an `amount` field that could be an `XrpCurrencyAmount` or an `IssuedCurrencyAmount`, so I would prefer having this pulled up into `CurrencyAmount` or `XrpCurrencyAmount`

File: xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/IssuedCurrencyAmount.java [hunk 2]
```diff
@@ -32,8 +37,8 @@
   String currency();
```
Comment (nkramer44) [inline xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/IssuedCurrencyAmount.java:37]: Maybe this is worth a separate issue, but maybe we could deprecate this in favor of a `BigDecimal` typed field.  I'm assuming there is a way to configure Jackson to deserialize scientific notation correctly, which would make this field much more useful.

**Review by nkramer44 — CHANGES_REQUESTED** [review]

File: xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Wrappers.java [hunk 3]
```diff
@@ -118,12 +128,23 @@ public static XrpCurrencyAmount ofDrops(UnsignedLong drops) {
...
-      return this.value().toString();
+    /**
+     * Convert the supplied amount of XRP drops into a decimal value representing a value denominated in whole XRP
+     * units.
+     *
+     * @param xrpCurrencyAmount A {@link XrpCurrencyAmount} representing an amount of XRP drops.
+     *
+     * @return A {@link BigDecimal} representing a value denominated in whole XRP units.
+     */
+    static BigDecimal toXrp(final XrpCurrencyAmount xrpCurrencyAmount) {
```
Comment (nhartner) [inline xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Wrappers.java:145]: This would be more obvious and convenient to use as a default method on XrpCurrency. So I could do something like `payment.amountAsXrp().toBigDecimal()` rather than `XrpCurrencyAmount.toXrp(payment.amountAsXrp())`

File: xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/IssuedCurrencyAmount.java (hunk 2 above)
Comment (sappenin) [reply xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/IssuedCurrencyAmount.java:37]: I like that in principle because using a number here seems more "correct" -- although the one downside of that is that a developer couldn't easily use a `String` here in their own code (they would have to translate to a BigDecimal). Is that a problem?

@nkramer44 I'm curious to hear more about how you use this field in your day-to-day development around issued currencies. Any thoughts there?

Comment (sappenin) [reply xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/IssuedCurrencyAmount.java:37]: In any event, let's create an issue for this and capture the conversation there?

Comment (sappenin) [reply xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/IssuedCurrencyAmount.java:37]: There's also this new [Discussions](https://github.com/XRPLF/xrpl4j/discussions) thing from GH -- might be an interesting first topic.

File: xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Payment.java (hunk 1 above)
Comment (sappenin) [reply xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Payment.java]: Agreed. See latest commit here and let me know what you think?
https://github.com/XRPLF/xrpl4j/pull/68/commits/1dcd61f54b98b21a97053d05963a584efe7dc75d

File: xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Wrappers.java [hunk 4]
```diff
@@ -118,12 +128,23 @@ public static XrpCurrencyAmount ofDrops(UnsignedLong drops) {
      * @return An {@link XrpCurrencyAmount} of the amount of drops in {@code amount}.
      */
     public static XrpCurrencyAmount ofXrp(BigDecimal amount) {
-      return ofDrops(amount.scaleByPowerOfTen(6).toBigIntegerExact().longValue());
+      if (FluentCompareTo.is(amount).notEqualTo(BigDecimal.ZERO)) {
```
[the remark this answers is not in the document]
Comment (sappenin) [reply xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Wrappers.java:131]: This is fully covered via [this test](https://github.com/XRPLF/xrpl4j/pull/68/files#diff-1bc50528c47cee0e21b5161efe5d957673e2eacfab4e4622e86d56bea8a1f479R41).

File: xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/IssuedCurrencyAmount.java (hunk 2 above)
Comment (sappenin) [reply xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/IssuedCurrencyAmount.java:37]: Started a discussion thread here: https://github.com/XRPLF/xrpl4j/discussions/72

File: xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Wrappers.java (hunk 3 above)
Comment (sappenin) [reply xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Wrappers.java]: Agree, great suggestion! Changed [here](https://github.com/XRPLF/xrpl4j/pull/68/commits/195c7a87fd2bbb5c31e54353fb9ca56674c4415d).

**Review by nkramer44 — APPROVED** [review]

File: xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Wrappers.java (hunk 3 above)
Comment (nhartner) [reply xrpl4j-model/src/main/java/org/xrpl/xrpl4j/model/transactions/Wrappers.java]: 👍

**Review by nhartner — APPROVED** [review]
bueno
